### PR TITLE
Adding Check for detector name for portexhaustion vs portrejections

### PR DESCRIPTION
**Pull request by puneetg1983**

### CODE REVIEW

**Comment by stevenernst131** [comment]
This solution is not going to work. You would have to wait for the getDetectors response before making the call to getSummaryViewModel(this.ConnectionsRejections, ...)

**Comment by puneetg1983** [comment]
Interesting, I thought that assigning it to an member variable (this.something) causes the two way binding to take care of it automatically as it worked locally at my end but I may be wrong then.

Since this is going to be throw away code , for now, shall I just move the call to getdetectorresponse in the subscribe block of the first call ???

**Comment by stevenernst131** [comment]
I think if you pass this.something to a member function, then that value is passed to the function as a local variable, it would not just all the sudden change the value of a parameter in a function midway through execution. 

Yes I think that is a better solution.

**Comment by puneetg1983** [comment]
lemme know if this looks ok

**Comment by stevenernst131** [comment]
This should work

**Pull request merged**
